#!/bin/bash

# Prevent pushing to the main branch
PROTECTED_BRANCH='main'
CURRENT_BRANCH=$(git branch --show-current)

if [ "$CURRENT_BRANCH" = "$PROTECTED_BRANCH" ]; then
  echo "You are not allowed to push to the $PROTECTED_BRANCH branch."
  exit 1
fi

# Check for leaks
gitleaks protect --verbose --staged